### ISSUE TITLE
Dispatcher Error

### ISSUE THREAD

**Issue by masterfung** [auth0/react-flux-jwt-authentication-sample#3]
I am getting `TypeError: this.$Dispatcher_callbacks[id] is not a function` when serving the page.

I am following along your tuts but I am getting the error above. I had to change a few things on my end. Here is the link to the github link: https://github.com/masterfung/react-flux-login

**Comment by mgonto** [comment]
Hey,

I'm not getting that error :(. Where are you getting it? What did you have to change?

Thanks for the report!

**Comment by masterfung** [comment]
i managed to solve it once i reinstalled my npm. its all good now! Thanks!
